Add final ranking
PatrykHub/ELECTRE-Methods pull request #41
Opened 2022-10-29 19:39 UTC by a-pralat

:)

2022-10-29 20:11 UTC, agak33 requested changes

2022-10-29 20:11 UTC, agak33 commented on mcda/plot/plot.py
> +        return "Directed Acyclic Graph required for transitive_reduction"
Wouldn't it be better if we return `None` when cannot build a graph? Here about [warnings](https://docs.python.org/3.8/library/warnings.html)

2022-10-29 20:11 UTC, agak33 commented on tests/test_distillation.py
> +    assert order_to_outranking_matrix(upward_order).equals(upward_order_matrix)
These should be two separate tests

2022-10-29 20:55 UTC, agak33 requested changes

2022-10-29 20:55 UTC, agak33 commented on mcda/plot/plot.py
> +    return graph
this return is unnecessary

2022-10-29 20:59 UTC, a-pralat commented on mcda/plot/plot.py
> +    return graph
X D ...

2022-10-29 21:20 UTC, agak33 approved these changes
OMG !!!!

2022-10-31 09:09 UTC, PatrykHub approved these changes

2022-11-02 09:29 UTC, merged