Fix credibility and add missing non-discordance equations
PatrykHub/ELECTRE-Methods pull request #46
Opened 2022-11-21 18:21 UTC by a-pralat

2022-11-23 13:39 UTC, agak33 approved these changes
chyba ok XD

2022-11-26 10:19 UTC, TomaszBud approved these changes

2022-11-26 10:21 UTC, PatrykHub requested changes

2022-11-26 10:21 UTC, PatrykHub commented on mcda/electre/discordance.py
> +    return_marginals: bool = False,
Wiem, że dokumentacja dokładniejsza będzie potem, ale dorzucenie do listy parametrów w niej żeby się nie zgubiło.

2022-11-26 10:21 UTC, PatrykHub commented on mcda/electre/discordance.py
> +    return_marginals: bool = False,
To samo co wyżej.

2022-11-26 10:30 UTC, PatrykHub approved these changes

2022-11-26 10:31 UTC, merged