Creating case study
PatrykHub/ELECTRE-Methods pull request #64
Opened 2023-01-05 01:00 UTC by PatrykHub

2023-01-07 14:01 UTC, agak33 requested changes
pls change the file name to something more descriptive and fix the part where an exception is raised

2023-01-07 23:30 UTC, agak33 approved these changes

2023-01-07 23:54 UTC, agak33 commented on mcda/electre/credibility.py
> +        discordance = 1 - discordance
Haven't we talked that such things should be AFTER THE VALIDATION?

2023-01-07 23:57 UTC, agak33 commented on mcda/electre/outranking/crisp_outranking.py
> +    table: pd.DataFrame,
I'd prefer a little bit more descriptive name than just `table`. Maybe something like `index_table`? :3

2023-01-08 11:33 UTC, a-pralat requested changes
Please make changes from Aga's comments

2023-01-08 13:49 UTC, agak33 requested changes

2023-01-08 13:49 UTC, agak33 commented on mcda/electre/outranking/crisp_outranking.py
> +                for alt_name_b in indices_table.index.values
```suggestion
                for alt_name_b in indices_table.columns.values
```

2023-01-08 13:49 UTC, agak33 commented on mcda/electre/outranking/crisp_outranking.py
> +        columns=indices_table.index,
```suggestion
        columns=indices_table.columns,
```

2023-01-12 08:27 UTC, a-pralat approved these changes

2023-01-12 08:49 UTC, merged